### ISSUE TITLE
Examples using get_local should use local.get

### ISSUE THREAD

**Issue by pjmlp** [PacktPublishing/Practical-WebAssembly#6]
The Webassembly standard renamed _get_local_ into local.get and the examples using it fail in modern wat2wasm versions, e.g 1.0.29

https://github.com/WebAssembly/spec/issues/884

```
user@host:~/Documents/wasm/wabt-playground$ ../wabt/bin/wat2wasm add.wat 
add.wat:3:3: error: unexpected token get_local, expected ).
		get_local $lhs
  ^^^^^^^^^
add.wat:4:3: error: unexpected token get_local.
		get_local $rhs
  ^^^^^^^^^
```

Fix is to use _local.get_ instead.

**Comment by shruthis-shetty** [comment]
Hi @pjmlp ,
The code has become outdated because of the underlying library change.
